### ISSUE TITLE
Desarrollar el constructor y destructor de la clase Queue

### ISSUE THREAD

**Issue by ricardgo403** [Abril-Barrera/Queue#2]
# Constructor
- Tipo de dato a almacenar
- Inicializar el array
- Capacity
- Counter
# Destructor
- Eliminar todas las referencias de memoria

**Comment by Abril-Barrera** [comment]
Me parece bien la descirpcion Joel, es tuya la parte, te la asigné cuando la tengas haces el pull

**Comment by ricardgo403** [comment]
Perfecto, en realidad ya tengo un código que podría resolver este issue. He ligado el PR con el issue.
Ojalá sea la solución correcta, de no ser así hazmelo saber y lo modifico.
Saludos,
